name: Security Scanner
description: Generates and uploads SARIF files to GitHub Advanced Security.
author: Workiva

inputs:
  scanner:
    description: 'Static code analysis tool to use. Options: semgrep'
    required: false
    default: semgrep

runs:
  using: composite
  steps:
    - name: 'Set up Python'
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: 'Set up Node'
      uses: actions/setup-node@v6
      with:
        node-version: '22.20.0'
        package-manager-cache: false
    - name: 'Generate SARIF file'
      run: node '${{ github.action_path }}/dist/index.js'
      env:
        INPUT_SCANNER: '${{ inputs.scanner }}'
      shell: bash
    - name: 'Upload SARIF file as artifact'
      uses: actions/upload-artifact@v5
      with:
        name: semgrep.sarif
        path: semgrep.sarif
    - name: 'Upload SARIF file to GitHub Advanced Security'
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: semgrep.sarif
