name: Security Scanner
description: Generates and uploads SARIF files to GitHub Advanced Security.
author: Workiva

inputs:
  scanner:
    description: 'Static code analysis tool to use. Options: semgrep'
    required: false
    default: semgrep

runs:
  using: composite
  steps:
    - name: 'Set up Node'
      uses: actions/setup-node@v6
      with:
        node-version: '24.13.0'
        package-manager-cache: false
    - name: 'Generate SARIF file'
      id: upload
      run: node '${{ github.action_path }}/dist/index.js'
      env:
        INPUT_SCANNER: '${{ inputs.scanner }}'
        INPUT_GITHUB-TOKEN: ${{ github.token }}
      shell: bash
    - name: 'Dismiss suppressed finding alerts'
      uses: advanced-security/dismiss-alerts@v2.0.2
      with:
        sarif-file: semgrep.sarif
        sarif-id: ${{ steps.upload.outputs.sarif-id }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
