# In TypeScript actions, `dist/` is a special directory. When you reference an
# action with the `uses` syntax, `dist/index.js` is the code that will be run
# (see action.yml).
#
# For this project, the `dist/index.js` file is transpiled from other source
# files. This workflow ensures the `dist/` directory contains the expected
# transpiled code.
name: Check dist/

on: [pull_request]

permissions:
  contents: read
  id-token: write

jobs:
  check-dist:
    runs-on: [self-hosted, xs]
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up Node'
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - name: 'Install dependencies'
        run: npm ci
      - name: 'Build dist/ directory'
        run: npm run bundle
      # The following will fail if the `dist/` directory differs from the
      # committed `dist/` directory.
      - name: 'Compare expected and actual dist/ directories'
        id: diff
        run: |
          if [ ! -d dist/ ]; then
            echo "Expected dist/ directory does not exist. See status below:"
            ls -la ./
            exit 1
          fi
          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See diff below:"
            git diff --ignore-space-at-eol --text dist/
            exit 1
          fi
