name: Continuous Integration

on:
  push:
    branches:
      - 'master'
      - 'experiments/**/*'
      - '_integration/**/*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  actions: read # Allow upload-sarif to get the action run status
  contents: read # Required for actions/checkout
  id-token: write # Required for requesting the OIDC token
  security-events: write # Allow upload-sarif to upload the SARIF file

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: small-al2023

    steps:
      - name: Setup Credentials
        uses: Workiva/gha-setup-credentials@v2.1.1

      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

      - uses: Workiva/gha-upload-test-reports@v2.0.17

      # Check dist
      - name: Build dist/ Directory
        id: build
        run: npm run bundle

      # This will fail the workflow if the `dist/` directory is different than
      # expected.
      - name: Compare Directories
        id: diff
        run: |
          if [ ! -d dist/ ]; then
            echo "Expected dist/ directory does not exist.  See status below:"
            ls -la ./
            exit 1
          fi
          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff --ignore-space-at-eol --text dist/
            exit 1
          fi

      # If `dist/` was different than expected, upload the expected version as a
      # workflow artifact.
      - if: ${{ failure() && steps.diff.outcome == 'failure' }}
        name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  test-action:
    name: GitHub Actions Test
    runs-on: small-al2023

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Test Local Action
        id: test-action
        uses: ./

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"

  semgrep:
    # User definable name of this GitHub Actions job.
    name: semgrep/ci
    # If you are self-hosting, change the following `runs-on` value:
    runs-on: xs-al2023

    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: semgrep/semgrep

    steps:
      # Fetch project source with GitHub Actions Checkout. Use either v3 or v4.
      - uses: actions/checkout@v5
      # Run the "semgrep ci" command on the command line of the docker image.
      - run: |
          unset HTTP_PROXY
          unset http_proxy
          unset HTTPS_PROXY
          unset https_proxy
          semgrep \
            --quiet \
            --config auto \
            --sarif \
            --sarif-output semgrep.sarif \
            --output /dev/null \
            --exclude-rule generic.secrets.security.detected-aws-access-key-id-value.detected-aws-access-key-id-value \
            --exclude-rule generic.secrets.security.detected-jwt-token.detected-jwt-token \
            --exclude-rule generic.secrets.security.detected-aws-account-id.detected-aws-account-id \
            --exclude-rule yaml.docker-compose.security.no-new-privileges.no-new-privileges \
            --exclude-rule yaml.docker-compose.security.writable-filesystem-service.writable-filesystem-service \
            --exclude-rule yaml.kubernetes.security.run-as-non-root.run-as-non-root \
            --exclude-rule generic.secrets.security.detected-private-key.detected-private-key
