name: CI

on: [push, pull_request]

permissions:
  actions: read # Allow upload-sarif to get the action run status
  contents: read # Required for actions/checkout
  id-token: write # Required for requesting the OIDC token
  security-events: write # Allow upload-sarif to upload the SARIF file

jobs:
  test-typescript:
    runs-on: [self-hosted, small]
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up Node'
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - name: 'Install dependencies'
        run: npm ci
      - name: 'Check formatting'
        run: npm run format:check
      - name: 'Lint'
        run: npm run lint
      - name: 'Test'
        run: npm run test
      - uses: Workiva/gha-upload-test-reports@v2.0.9
  test-action:
    runs-on: [self-hosted, dev-small]
    steps:
      - uses: actions/checkout@v4
      - name: 'Test local action'
        uses: ./
