name: Semgrep

"on":
  pull_request:
    branches-ignore:
      - '_integration/**/*'
  push:
    branches:
      - master
      - main

permissions:
  contents: read # Required for actions/checkout
  actions: read # Allow upload-sarif to get the action run status
  security-events: write # Allow upload-sarif to upload the SARIF file

jobs:
  semgrep:
    runs-on: [self-hosted, medium, al2023]
    steps:
      - uses: actions/checkout@v4
      - uses: Workiva/gha-security-scanner@Red-6766-push-master-main
