name: Run renovate on k8s-actions-runner
on:
  schedule:
    - cron: '0 15 * * 4'

permissions:
  contents: read
  id-token: write

jobs:
  renovate:
    runs-on: xs-al2023
    steps:
      - uses: actions/checkout@v6
      - uses: Workiva/gha-setup-credentials@v2.1.9
      - id: create-github-app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: Iv23lifgkfjrNu04SiEC
          private-key: ${{ secrets.RENOVATE_GH_APP_PRIVATE_KEY }}
          owner: Workiva # This is needed for the target repo to read gha-security
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.13
        with:
          token: ${{ steps.create-github-app-token.outputs.token }}
          configurationFile: 'renovate.json'
        env:
          LOG_LEVEL: info
